"""
"""
class Constant:
    PLACEHOLDER_OFFSET = 1048576
    MAX_ADDRESS = 65535
    INVALID_VALUE = 0xDECAFBEEFABCDEFF
    UNDETERMINED = -1
    UNUSED = -2
    PH_8BIT_IMMEDIATE = "d8"
    PH_16BIT_IMMEDIATE = "d16"
    PH_8BIT_UNSIGNED = "a8"
    PH_16BIT_ADDRESS = "a16"
    PH_8BIT_SIGNED_REL = "r8"
